@host= http://localhost:8081/api/v1/list
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUyODM3NDE1LCJleHAiOjE2NTMwMTAyMTV9.UVNXlFnCdGEC47NG-y1G-LR160jCOtU84r0mUw4TKyA
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyODA0NTEyLCJleHAiOjE2NTI5NzczMTJ9.9O4BBpKRMiZGFfy7CmVIhMDA6LB_do06c209EPRTVyc

### user lists
GET {{host}}
authorization: {{token1}}

### crear lista de peliculas
POST {{host}}/create
authorization: {{token1}}
Content-Type: application/json

{
    "name": "Accion"
}

### rename lista de peliculas
PUT {{host}}/update/1
authorization: {{token1}}
Content-Type: application/json

{
    "name": "Romance"
}

### borrar lista de peliculas
DELETE {{host}}/delete/1
authorization: {{token1}}
