@host= http://localhost:8081/api/v1/list
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUyNzQ4MTYwLCJleHAiOjE2NTI5MjA5NjB9.8VEJyJsA_ELa-htnN07USR86uMxgKEwpE9OrMBknJ88
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjUyNzQ4MTg4LCJleHAiOjE2NTI5MjA5ODh9.vfqHwqwCjiWQTCM4ShtZ2zHk6zIsaCmqAU2tLB5_L7A

### user lists
GET {{host}}
authorization: {{token1}}

### crear lista de peliculas
POST {{host}}/create
authorization: {{token1}}
Content-Type: application/json

{
    "name": "New List"
}

### crear lista de peliculas
PUT {{host}}/update/1
authorization: {{token1}}
Content-Type: application/json

{
    "name": "Accion"
}

### borrar lista de peliculas
DELETE {{host}}/delete/1
authorization: {{token1}}
