@listID = 1
@host= http://localhost:8081/api/v1/list/{{listID}}/movies
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUyODA0NDYxLCJleHAiOjE2NTI5NzcyNjF9.ZbkxuWJJmgerf1OSfdY8KjVDzpipMzKoAZigZAJv9Bc
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyODA0NTEyLCJleHAiOjE2NTI5NzczMTJ9.9O4BBpKRMiZGFfy7CmVIhMDA6LB_do06c209EPRTVyc
### obtener peliculas de una lista
GET {{host}}
authorization: {{token1}}

### Añadir pelicula a la lista
POST {{host}}/add/80
authorization: {{token1}}


### Eliminar pelicula de la lista
DELETE {{host}}/remove/1201
authorization: {{token1}}