@host= http://localhost:8081/api/v1/user
### crear usuario
POST  {{host}}/register
Content-Type: application/json

{
"name": "user2",
"password": "123",
"passwordConfirm": "123"
}
### login sin token
POST {{host}}/login
Content-Type: application/json

{
"name": "user2",
"password": "123"
}
### login con token
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUzNTEwNTkzLCJleHAiOjE2NTM2ODMzOTN9.sNpc94bOOQ8Z6D3tKGOn8XgBTRMhm60fP6wI5sZ-F1o
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjUyODA0NTEyLCJleHAiOjE2NTI5NzczMTJ9.9O4BBpKRMiZGFfy7CmVIhMDA6LB_do06c209EPRTVyc

POST {{host}}/login
authorization: {{token1}}

### user info
GET {{host}}/info
authorization: {{token1}}

