@host= http://localhost:8081/api/v1/user
### crear usuario
POST  {{host}}/register
Content-Type: application/json

{
"name": "user1",
"password": "123",
"passwordConfirm": "123"
}
### login sin token
POST {{host}}/login
Content-Type: application/json

{
"name": "user2",
"password": "123"
}
### login con token
@token1=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjUyNzUxMTE4LCJleHAiOjE2NTI5MjM5MTh9.innXVBy7iFd5qEjlMziv0OyRPqXerZhJX2VrAP9naEw
@token2=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjUyNzQ4MTg4LCJleHAiOjE2NTI5MjA5ODh9.vfqHwqwCjiWQTCM4ShtZ2zHk6zIsaCmqAU2tLB5_L7A

POST {{host}}/login
authorization: {{token1}}

### user info
GET {{host}}/info
authorization: {{token1}}

